### ISSUE TITLE
safari에서 facebook login이 되지 않는 문제

### ISSUE THREAD

**Issue by wonseokyang** [gomicorp/YAC#1]
위치: pc, mobile의 safari
증상: comment를 작성하기 위해 facebook login 후, gomistore.vn 으로 리다이렉트된 후 로그인 되어있지 않음.
특이사항: 콘솔에서 아무런 에러 로그를 뿜지 않음.

**Comment by yhk1038** [comment]
사파리에서는 동작하지 않는걸로!
